  language: node_js
  node_js:
  - "node"
  install:
    - npm install
  script:
    - npm run test
  cache:
    directories:
      - "node_modules"
      
  after_success: npm run coveralls
  # whitelist
  branches:
    only:
      - master
      - develop